uart:
  baud_rate: 3780
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_pin: GPIO05
  tx_pin: GPIO06
  #debug:

external_components:
  - source: github://baedev1106/esp-wallpad@latest
    components: [ uartex ]
    refresh: always

uartex:
  rx_timeout: 30ms
  tx_delay: 50ms
  tx_timeout: 500ms
  tx_retry_cnt: 3

  rx_header: [0x7F]
  rx_footer: [0xEE]
  tx_header: [0x7F]
  tx_footer: [0xEE]

  version:
    disabled: False
  error:
    disabled: False
  log:
    disabled: False

# (W: Wallpad, S: Sub 주방폰)
# ​
# 7F B4 00 00 EE // W <- S 문열림 (통화중에만 가능)
# ​
# 7F B5 00 00 EE // W -> S 현관 문 호출
# 7F B6 00 00 EE // W -> S 현관 문 호출 끝
# ​
# 7F B9 00 00 EE // W <- S 통화 열기 (주방폰 발신)
# 7F BA 00 00 EE // W <- S 통화 열기 끝 (주방폰 발신)
# ​
# 7F BB 00 00 EE // W -> S 다른 통화가 있음
# ​
# 7F B7 00 00 EE // W <- S 통화 수신
# 7F B8 00 00 EE // W <- S 통화 종료
# ​
# 7F 5A 00 00 EE // W -> S 공동현관문 호출
# 7F 5C 00 00 EE // W -> S 공동현관문 호출 끝
# ​
# 7F 5F 00 00 EE // W <- S 공동현관문 호출 수신
# ​
# 7F 61 00 00 EE // W <- S 공동현관문 열기 (통화중에만 가능)
# 7F 60 00 00 EE // W <- S 통화 종료
# ​
# ​
# 호출이 온 경우 문을 열려면
# 7F B7 00 00 EE // W <- S 통화 수신
# 7F B4 00 00 EE // W <- S 문열림
# 7F B8 00 00 EE // W <- S 통화 종료
# ​
# 통화 없이 문을 열려면
# 7F B9 00 00 EE // W <- S 통화 열기 (주방폰 발신)
# 7F B4 00 00 EE // W <- S 문열림
# 7F BA 00 00 EE // W <- S 통화 열기 끝 (주방폰 발신)
# ​
# 공동현관문은 통화 없이는 문을 열 수 없기에 외부에서 호출이 와야만 열 수 있습니다.
# 7F 5F 00 00 EE // W <- S 공동현관문 호출 수신
# 7F 61 00 00 EE // W <- S 공동현관문 열기 (통화중에만 가능)
# 7F 60 00 00 EE // W <- S 통화 종료

binary_sensor:
  - platform: uartex
    id: id_door_bell
    name: "Door Bell"
    icon: "mdi:bell-ring"
    state:
      data: [0xB4, 0x00, 0x00]
      mask: [0xB4, 0xFF, 0xFF]
    state_on:
      offset: 0
      data: [0xB5]
    state_off:
      offset: 0
      data: [0xB6]
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: id_door_bell
            then:
              - delay: 2s
              - lambda: |-
                  id(id_door_bell).publish_state(false);

  - platform: uartex
    id: id_door_bell_common
    name: "Door Bell Common"
    icon: "mdi:bell-ring"
    state:
      data: [0x58, 0x00, 0x00]
      mask: [0x58, 0xFF, 0xFF]
    state_on:
      offset: 0
      data: [0x5A]
    state_off:
      offset: 0
      data: [0x5C]
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: id_door_bell_common
            then:
              - script.execute: open_common_door_sequence
              - delay: 2s
              - lambda: |-
                  id(id_door_bell_common).publish_state(false);

button:
  - platform: uartex
    id: id_door_open_common
    name: "Door Open Common"
    icon: "mdi:door-sliding-open"
    command_on: 
      data: [0x61, 0x00, 0x00]

switch:
  - platform: uartex
    id: id_door_call_common
    name: "Door Call Common"
    icon: "mdi:phone"
    command_on: 
      data: [0x5F, 0x00, 0x00]
    command_off: 
      data: [0x60, 0x00, 0x00]
  - platform: template
    id: id_enable_auto_open_common
    name: "Auto Door Opener Common"
    icon: "mdi:door-open"
    optimistic: True
    restore_mode: ALWAYS_ON
    on_turn_off:
      then:
        - script.stop: open_common_door_sequence

script:
  - id: open_common_door_sequence
    then:
      - if:
          condition:
            - switch.is_on: id_enable_auto_open_common
          then:
            - delay: 500ms
            - switch.turn_on: id_door_call_common
            - delay: 500ms
            - button.press: id_door_open_common
            - delay: 500ms
            - switch.turn_off: id_door_call_common